### PR TITLE
rejig accordionitem

### LINKED ISSUE #58: separating AccordianItem from Accordian doesn't work
When I try to put the AccordianItem component separate from the Accordian component, the AccordianItem doesn't expand. For example, my render function of the AccordianItem is defined as: 

```javascript
import { AccordionItem } from 'react-sanfona';

export default class Learnable extends Component {

....

render() {
return (
      <AccordionItem title={this.props.tags[0]} key={this.props.learnableid}  >
          <div>
            {this.props.text}
          </div>
      </AccordionItem>
    );
  }
}
```
and then my Accordian is defined as: 
```javascript
import Learnable from './Learnable';
import { Accordion } from 'react-sanfona';

export default class LearnableList2 extends Component {

... 

render() {
    const { learnables } = this.props;
    const learnablesList = learnables.map((learnable) => <Learnable key={learnable.id} learnableid={learnable.id} text={learnable.text} tags={learnable.tags} />);
    return (
      <Accordion allowMultiple >
        {learnablesList}
      </Accordion>
    );
  }
}
```

When I do this, only the title of each AccordianItem shows up, but if I try to expand the item, it doesn't expand. 

However, if I put the Accordian and AccordianItem in one file like you do in the demo examples, it works perfectly.

 Is there anything I'm doing wrong?

### PR DESCRIPTION
**Pull request by psimyn**
animation duration to body as props
cancelable open/open
allow wrapping AccordionItem in another component. should fix #58

### CODE REVIEW

File: src/AccordionItem/index.jsx [hunk 1]
```diff
@@ -14,69 +14,76 @@ export default class AccordionItem extends Component {
     super(props);
     this.state = {
```
Comment (choonkending) [inline src/AccordionItem/index.jsx]: `const { expanded } = this.props;`

File: src/AccordionItem/index.jsx [hunk 2]
```diff
@@ -117,7 +124,9 @@ export default class AccordionItem extends Component {
           onClick={this.props.onClick}
           titleColor= {this.props.titleColor}
           uuid={this.uuid} />
```
Comment (choonkending) [inline src/AccordionItem/index.jsx]:
```javascript
const { titleClassName, title, onClick, titleColor, bodyClassName } = this.props;
const { maxHeight, duration, overflow } = this.state;
```
